// MASSIVELY EXPANDED Comprehensive dummy data for admin side
// This file will be copied to adminDummyData.js

// Helper function to generate dates
const getDate = (daysOffset = 0) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

const getDateTime = (daysOffset = 0, hoursOffset = 0) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  date.setHours(date.getHours() + hoursOffset);
  return date.toISOString();
};

// Avatar helper
const mkAvatar = (name, bg = "8B2332") =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=FFFFFF&bold=true&size=128`;

// Note: Include the expanded ADMIN_USERS array from previous
// Note: Include the expanded ADMIN_REGISTRATIONS array from previous

// ====================================
// COMPREHENSIVE AGREEMENTS - 60+ INSTITUTIONS FROM ALL CONTINENTS
// ====================================
export const ADMIN_AGREEMENTS = [
  // ========== EASTERN ASIA ==========
  {
    agreement_id: 1,
    dts_number: "DTS-2024-001",
    document_type: "MOU",
    title: "Academic Cooperation in Engineering",
    partner_name: "Tokyo International University",
    institution_name: "Tokyo International University",
    country: "Japan",
    region: "Eastern Asia",
    partnership_type: "Academic Exchange",
    scope_of_partnership: ["Student Exchange", "Faculty Exchange", "Joint Research"],
    date_signed: getDate(-180),
    date_expiry: getDate(185),
    validity_period: "1 year",
    entry_date: getDate(-180),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Engineering and technology cooperation program.",
    point_person_name: "Prof. John Reyes",
    point_person_email: "john.reyes@university.edu",
    point_person_phone: "+63-2-8888-1235",
    contact_person_name: "Dr. Hiroshi Tanaka",
    contact_person_email: "h.tanaka@tiu.ac.jp",
    contact_person_phone: "+81-3-1234-5678",
    university_logo: mkAvatar("Tokyo International University", "C62828"),
    logo: mkAvatar("Tokyo International University", "C62828"),
    file_path: "/documents/DTS-2024-001.pdf",
    created_at: getDateTime(-180),
    updated_at: getDateTime(-10),
    created_by: "Dr. Maria Santos",
    updated_by: "Prof. John Reyes",
  },
  {
    agreement_id: 2,
    dts_number: "DTS-2023-098",
    document_type: "MOU",
    title: "Student Exchange Program",
    partner_name: "Seoul National University",
    institution_name: "Seoul National University",
    country: "South Korea",
    region: "Eastern Asia",
    partnership_type: "Student Mobility",
    scope_of_partnership: ["Student Exchange", "Scholarship Programs"],
    date_signed: getDate(-280),
    date_expiry: getDate(85),
    validity_period: "1 year",
    entry_date: getDate(-280),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Student mobility and scholarship opportunities.",
    point_person_name: "Prof. John Reyes",
    point_person_email: "john.reyes@university.edu",
    point_person_phone: "+63-2-8888-1235",
    contact_person_name: "Dr. Kim Min-jun",
    contact_person_email: "kmj@snu.ac.kr",
    contact_person_phone: "+82-2-880-5114",
    university_logo: mkAvatar("Seoul National University", "003A70"),
    logo: mkAvatar("Seoul National University", "003A70"),
    file_path: "/documents/DTS-2023-098.pdf",
    created_at: getDateTime(-280),
    updated_at: getDateTime(-20),
    created_by: "Dr. Maria Santos",
    updated_by: "Prof. John Reyes",
  },
  {
    agreement_id: 3,
    dts_number: "DTS-2024-076",
    document_type: "MOA",
    title: "Research Collaboration in AI",
    partner_name: "Tsinghua University",
    institution_name: "Tsinghua University",
    country: "China",
    region: "Eastern Asia",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Technology Transfer", "Student Exchange"],
    date_signed: getDate(-150),
    date_expiry: getDate(580),
    validity_period: "2 years",
    entry_date: getDate(-150),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "AI and machine learning research partnership.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. Li Wei",
    contact_person_email: "liwei@tsinghua.edu.cn",
    contact_person_phone: "+86-10-6278-1234",
    university_logo: mkAvatar("Tsinghua University", "6A1B9A"),
    logo: mkAvatar("Tsinghua University", "6A1B9A"),
    file_path: "/documents/DTS-2024-076.pdf",
    created_at: getDateTime(-150),
    updated_at: getDateTime(-12),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 4,
    dts_number: "DTS-2025-014",
    document_type: "MOU",
    title: "Business School Partnership",
    partner_name: "National Taiwan University",
    institution_name: "NTU",
    country: "Taiwan",
    region: "Eastern Asia",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Dual Degree Programs", "Faculty Exchange"],
    date_signed: getDate(-45),
    date_expiry: getDate(320),
    validity_period: "1 year",
    entry_date: getDate(-45),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Business administration dual degree program.",
    point_person_name: "Dr. Sarah Chen",
    point_person_email: "sarah.chen@university.edu",
    point_person_phone: "+63-2-8888-1236",
    contact_person_name: "Prof. Chang Yu-ting",
    contact_person_email: "ytchang@ntu.edu.tw",
    contact_person_phone: "+886-2-3366-1234",
    university_logo: mkAvatar("National Taiwan University", "543C8A"),
    logo: mkAvatar("National Taiwan University", "543C8A"),
    file_path: "/documents/DTS-2025-014.pdf",
    created_at: getDateTime(-45),
    updated_at: getDateTime(-5),
    created_by: "Dr. Sarah Chen",
    updated_by: "Dr. Sarah Chen",
  },
  {
    agreement_id: 5,
    dts_number: "DTS-2024-089",
    document_type: "MOU",
    title: "Medical Sciences Cooperation",
    partner_name: "University of Hong Kong",
    institution_name: "HKU",
    country: "Hong Kong",
    region: "Eastern Asia",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Faculty Exchange", "Clinical Training"],
    date_signed: getDate(-100),
    date_expiry: getDate(265),
    validity_period: "1 year",
    entry_date: getDate(-100),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Medical research and clinical training collaboration.",
    point_person_name: "Dr. Aisha Rahman",
    point_person_email: "a.rahman@university.edu",
    point_person_phone: "+63-2-8888-1240",
    contact_person_name: "Dr. Wong Kar-wai",
    contact_person_email: "kwwong@hku.hk",
    contact_person_phone: "+852-2859-1234",
    university_logo: mkAvatar("University of Hong Kong", "0F6C35"),
    logo: mkAvatar("University of Hong Kong", "0F6C35"),
    file_path: "/documents/DTS-2024-089.pdf",
    created_at: getDateTime(-100),
    updated_at: getDateTime(-15),
    created_by: "Dr. Aisha Rahman",
    updated_by: "Dr. Aisha Rahman",
  },

  // ========== SOUTH-EASTERN ASIA ==========
  {
    agreement_id: 6,
    dts_number: "DTS-2024-015",
    document_type: "MOU",
    title: "Engineering Education Partnership",
    partner_name: "National University of Singapore",
    institution_name: "NUS",
    country: "Singapore",
    region: "South-Eastern Asia",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Faculty Exchange", "Curriculum Development"],
    date_signed: getDate(-335),
    date_expiry: getDate(30),
    validity_period: "1 year",
    entry_date: getDate(-335),
    status: "NEARING_EXPIRATION",
    agreement_status: "Active",
    description: "Engineering curriculum development partnership.",
    point_person_name: "Dr. Sarah Chen",
    point_person_email: "sarah.chen@university.edu",
    point_person_phone: "+63-2-8888-1236",
    contact_person_name: "Prof. Lee Wei Ming",
    contact_person_email: "weiming.lee@nus.edu.sg",
    contact_person_phone: "+65-6516-6666",
    university_logo: mkAvatar("NUS", "003D7C"),
    logo: mkAvatar("NUS", "003D7C"),
    file_path: "/documents/DTS-2024-015.pdf",
    created_at: getDateTime(-335),
    updated_at: getDateTime(-25),
    created_by: "Prof. John Reyes",
    updated_by: "Dr. Sarah Chen",
  },
  {
    agreement_id: 7,
    dts_number: "DTS-2025-008",
    document_type: "MOU",
    title: "Cultural and Educational Exchange",
    partner_name: "University of the Philippines Diliman",
    institution_name: "UP Diliman",
    country: "Philippines",
    region: "South-Eastern Asia",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs", "Faculty Development"],
    date_signed: getDate(-60),
    date_expiry: getDate(305),
    validity_period: "1 year",
    entry_date: getDate(-60),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Bilateral cultural and educational collaboration.",
    point_person_name: "James Rodriguez",
    point_person_email: "james.rodriguez@university.edu",
    point_person_phone: "+63-2-8888-1237",
    contact_person_name: "Dr. Maria Dela Cruz",
    contact_person_email: "mdelacruz@up.edu.ph",
    contact_person_phone: "+63-2-8981-8500",
    university_logo: mkAvatar("UP Diliman", "7B1113"),
    logo: mkAvatar("UP Diliman", "7B1113"),
    file_path: "/documents/DTS-2025-008.pdf",
    created_at: getDateTime(-60),
    updated_at: getDateTime(-2),
    created_by: "Prof. John Reyes",
    updated_by: "Prof. John Reyes",
  },
  {
    agreement_id: 8,
    dts_number: "DTS-2024-112",
    document_type: "MOA",
    title: "Tourism and Hospitality Partnership",
    partner_name: "Chulalongkorn University",
    institution_name: "Chulalongkorn",
    country: "Thailand",
    region: "South-Eastern Asia",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Student Exchange", "Joint Research", "Internship Programs"],
    date_signed: getDate(-90),
    date_expiry: getDate(275),
    validity_period: "1 year",
    entry_date: getDate(-90),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Tourism management and hospitality education partnership.",
    point_person_name: "Dr. Aisha Rahman",
    point_person_email: "a.rahman@university.edu",
    point_person_phone: "+63-2-8888-1240",
    contact_person_name: "Dr. Somchai Prasert",
    contact_person_email: "s.prasert@chula.ac.th",
    contact_person_phone: "+66-2-218-1234",
    university_logo: mkAvatar("Chulalongkorn", "FF1493"),
    logo: mkAvatar("Chulalongkorn", "FF1493"),
    file_path: "/documents/DTS-2024-112.pdf",
    created_at: getDateTime(-90),
    updated_at: getDateTime(-18),
    created_by: "Dr. Aisha Rahman",
    updated_by: "Dr. Aisha Rahman",
  },
  {
    agreement_id: 9,
    dts_number: "DTS-2024-134",
    document_type: "MOU",
    title: "Biotechnology Research Collaboration",
    partner_name: "University of Malaya",
    institution_name: "UM",
    country: "Malaysia",
    region: "South-Eastern Asia",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Technology Transfer"],
    date_signed: getDate(-75),
    date_expiry: getDate(290),
    validity_period: "1 year",
    entry_date: getDate(-75),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Biotechnology and pharmaceutical research partnership.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Dr. Ahmad bin Ibrahim",
    contact_person_email: "ahmad.ibrahim@um.edu.my",
    contact_person_phone: "+60-3-7967-1234",
    university_logo: mkAvatar("University of Malaya", "003C7E"),
    logo: mkAvatar("University of Malaya", "003C7E"),
    file_path: "/documents/DTS-2024-134.pdf",
    created_at: getDateTime(-75),
    updated_at: getDateTime(-8),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 10,
    dts_number: "DTS-2025-021",
    document_type: "MOU",
    title: "Agriculture and Food Science Partnership",
    partner_name: "Institut Pertanian Bogor",
    institution_name: "IPB University",
    country: "Indonesia",
    region: "South-Eastern Asia",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Student Exchange", "Joint Research", "Faculty Exchange"],
    date_signed: getDate(-35),
    date_expiry: getDate(330),
    validity_period: "1 year",
    entry_date: getDate(-35),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Agricultural sciences and sustainable food systems collaboration.",
    point_person_name: "Dr. Rajesh Kumar",
    point_person_email: "r.kumar@university.edu",
    point_person_phone: "+63-2-8888-1248",
    contact_person_name: "Prof. Siti Nurlaela",
    contact_person_email: "s.nurlaela@ipb.ac.id",
    contact_person_phone: "+62-251-8622-636",
    university_logo: mkAvatar("IPB University", "1B5E20"),
    logo: mkAvatar("IPB University", "1B5E20"),
    file_path: "/documents/DTS-2025-021.pdf",
    created_at: getDateTime(-35),
    updated_at: getDateTime(-3),
    created_by: "Dr. Rajesh Kumar",
    updated_by: "Dr. Rajesh Kumar",
  },
  {
    agreement_id: 11,
    dts_number: "DTS-2024-098",
    document_type: "MOU",
    title: "Economics and Development Studies",
    partner_name: "Vietnam National University",
    institution_name: "VNU Hanoi",
    country: "Vietnam",
    region: "South-Eastern Asia",
    partnership_type: "Academic Exchange",
    scope_of_partnership: ["Student Exchange", "Faculty Exchange"],
    date_signed: getDate(-110),
    date_expiry: getDate(255),
    validity_period: "1 year",
    entry_date: getDate(-110),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Economics and development studies exchange program.",
    point_person_name: "Prof. John Reyes",
    point_person_email: "john.reyes@university.edu",
    point_person_phone: "+63-2-8888-1235",
    contact_person_name: "Prof. Nguyen Van Minh",
    contact_person_email: "nv.minh@vnu.edu.vn",
    contact_person_phone: "+84-24-3558-1234",
    university_logo: mkAvatar("VNU Hanoi", "DA251D"),
    logo: mkAvatar("VNU Hanoi", "DA251D"),
    file_path: "/documents/DTS-2024-098.pdf",
    created_at: getDateTime(-110),
    updated_at: getDateTime(-22),
    created_by: "Prof. John Reyes",
    updated_by: "Prof. John Reyes",
  },
  {
    agreement_id: 12,
    dts_number: "DTS-2025-003",
    document_type: "MOA",
    title: "Islamic Studies and Education",
    partner_name: "Universiti Brunei Darussalam",
    institution_name: "UBD",
    country: "Brunei",
    region: "South-Eastern Asia",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Faculty Exchange", "Cultural Programs"],
    date_signed: getDate(-25),
    date_expiry: getDate(340),
    validity_period: "1 year",
    entry_date: getDate(-25),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Islamic studies and comparative religion programs.",
    point_person_name: "Prof. Ibrahim Hassan",
    point_person_email: "i.hassan@university.edu",
    point_person_phone: "+63-2-8888-1246",
    contact_person_name: "Dr. Haji Mahmud",
    contact_person_email: "h.mahmud@ubd.edu.bn",
    contact_person_phone: "+673-2-463-001",
    university_logo: mkAvatar("UBD", "003893"),
    logo: mkAvatar("UBD", "003893"),
    file_path: "/documents/DTS-2025-003.pdf",
    created_at: getDateTime(-25),
    updated_at: getDateTime(-1),
    created_by: "Prof. Ibrahim Hassan",
    updated_by: "Prof. Ibrahim Hassan",
  },

  // ========== SOUTHERN ASIA ==========
  {
    agreement_id: 13,
    dts_number: "DTS-2024-145",
    document_type: "MOA",
    title: "Technology and Innovation Partnership",
    partner_name: "Indian Institute of Technology Delhi",
    institution_name: "IIT Delhi",
    country: "India",
    region: "Southern Asia",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Student Exchange", "Technology Transfer"],
    date_signed: getDate(-65),
    date_expiry: getDate(665),
    validity_period: "2 years",
    entry_date: getDate(-65),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Technology innovation and engineering research partnership.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. Raj Sharma",
    contact_person_email: "raj.sharma@iitd.ac.in",
    contact_person_phone: "+91-11-2659-1234",
    university_logo: mkAvatar("IIT Delhi", "003D7C"),
    logo: mkAvatar("IIT Delhi", "003D7C"),
    file_path: "/documents/DTS-2024-145.pdf",
    created_at: getDateTime(-65),
    updated_at: getDateTime(-7),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 14,
    dts_number: "DTS-2024-167",
    document_type: "MOU",
    title: "Medical Education and Research",
    partner_name: "Aga Khan University",
    institution_name: "AKU",
    country: "Pakistan",
    region: "Southern Asia",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Faculty Exchange", "Joint Research", "Clinical Training"],
    date_signed: getDate(-55),
    date_expiry: getDate(310),
    validity_period: "1 year",
    entry_date: getDate(-55),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Medical education and healthcare research collaboration.",
    point_person_name: "Dr. Fatima Al-Mansouri",
    point_person_email: "f.almansouri@university.edu",
    point_person_phone: "+63-2-8888-1242",
    contact_person_name: "Dr. Zafar Ahmed",
    contact_person_email: "zafar.ahmed@aku.edu",
    contact_person_phone: "+92-21-3486-1234",
    university_logo: mkAvatar("Aga Khan University", "00704A"),
    logo: mkAvatar("Aga Khan University", "00704A"),
    file_path: "/documents/DTS-2024-167.pdf",
    created_at: getDateTime(-55),
    updated_at: getDateTime(-11),
    created_by: "Dr. Fatima Al-Mansouri",
    updated_by: "Dr. Fatima Al-Mansouri",
  },
  {
    agreement_id: 15,
    dts_number: "DTS-2025-027",
    document_type: "MOU",
    title: "Public Health and Community Development",
    partner_name: "University of Dhaka",
    institution_name: "DU",
    country: "Bangladesh",
    region: "Southern Asia",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Student Exchange"],
    date_signed: getDate(-20),
    date_expiry: getDate(345),
    validity_period: "1 year",
    entry_date: getDate(-20),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Public health research and community development programs.",
    point_person_name: "Dr. Aisha Rahman",
    point_person_email: "a.rahman@university.edu",
    point_person_phone: "+63-2-8888-1240",
    contact_person_name: "Prof. Rahman Chowdhury",
    contact_person_email: "r.chowdhury@du.ac.bd",
    contact_person_phone: "+880-2-9661-900",
    university_logo: mkAvatar("University of Dhaka", "006837"),
    logo: mkAvatar("University of Dhaka", "006837"),
    file_path: "/documents/DTS-2025-027.pdf",
    created_at: getDateTime(-20),
    updated_at: getDateTime(-2),
    created_by: "Dr. Aisha Rahman",
    updated_by: "Dr. Aisha Rahman",
  },
  {
    agreement_id: 16,
    dts_number: "DTS-2024-176",
    document_type: "MOU",
    title: "Environmental Sciences Partnership",
    partner_name: "University of Colombo",
    institution_name: "UOC",
    country: "Sri Lanka",
    region: "Southern Asia",
    partnership_type: "Academic Exchange",
    scope_of_partnership: ["Student Exchange", "Faculty Exchange", "Joint Research"],
    date_signed: getDate(-48),
    date_expiry: getDate(317),
    validity_period: "1 year",
    entry_date: getDate(-48),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Environmental conservation and climate research collaboration.",
    point_person_name: "Dr. Rajesh Kumar",
    point_person_email: "r.kumar@university.edu",
    point_person_phone: "+63-2-8888-1248",
    contact_person_name: "Prof. Nimal Fernando",
    contact_person_email: "n.fernando@cmb.ac.lk",
    contact_person_phone: "+94-11-251-2345",
    university_logo: mkAvatar("University of Colombo", "8B4513"),
    logo: mkAvatar("University of Colombo", "8B4513"),
    file_path: "/documents/DTS-2024-176.pdf",
    created_at: getDateTime(-48),
    updated_at: getDateTime(-9),
    created_by: "Dr. Rajesh Kumar",
    updated_by: "Dr. Rajesh Kumar",
  },

  // ========== WESTERN EUROPE ==========
  {
    agreement_id: 17,
    dts_number: "DTS-2024-022",
    document_type: "MOA",
    title: "Research and Innovation Partnership",
    partner_name: "Technical University of Munich",
    institution_name: "TU Munich",
    country: "Germany",
    region: "Western Europe",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Technology Transfer", "Student Exchange"],
    date_signed: getDate(-350),
    date_expiry: getDate(15),
    validity_period: "1 year",
    entry_date: getDate(-350),
    status: "NEARING_EXPIRATION",
    agreement_status: "Active",
    description: "Sustainable engineering and innovation partnership.",
    point_person_name: "Dr. Maria Santos",
    point_person_email: "maria.santos@university.edu",
    point_person_phone: "+63-2-8888-1234",
    contact_person_name: "Prof. Klaus Mueller",
    contact_person_email: "k.mueller@tum.de",
    contact_person_phone: "+49-89-289-01",
    university_logo: mkAvatar("TU Munich", "0065BD"),
    logo: mkAvatar("TU Munich", "0065BD"),
    file_path: "/documents/DTS-2024-022.pdf",
    created_at: getDateTime(-350),
    updated_at: getDateTime(-8),
    created_by: "Dr. Maria Santos",
    updated_by: "Dr. Maria Santos",
  },
  {
    agreement_id: 18,
    dts_number: "DTS-2024-188",
    document_type: "MOA",
    title: "Business and Economics Collaboration",
    partner_name: "Sorbonne University",
    institution_name: "Sorbonne",
    country: "France",
    region: "Western Europe",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Dual Degree Programs", "Faculty Exchange", "Joint Research"],
    date_signed: getDate(-72),
    date_expiry: getDate(658),
    validity_period: "2 years",
    entry_date: getDate(-72),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Business school and economics dual degree partnership.",
    point_person_name: "Prof. Michael O'Connor",
    point_person_email: "m.oconnor@university.edu",
    point_person_phone: "+63-2-8888-1241",
    contact_person_name: "Prof. Marie Dubois",
    contact_person_email: "m.dubois@sorbonne.fr",
    contact_person_phone: "+33-1-40-46-1234",
    university_logo: mkAvatar("Sorbonne", "003B5C"),
    logo: mkAvatar("Sorbonne", "003B5C"),
    file_path: "/documents/DTS-2024-188.pdf",
    created_at: getDateTime(-72),
    updated_at: getDateTime(-13),
    created_by: "Prof. Michael O'Connor",
    updated_by: "Prof. Michael O'Connor",
  },
  {
    agreement_id: 19,
    dts_number: "DTS-2024-007",
    document_type: "MOU",
    title: "Medical Sciences Research",
    partner_name: "University of Oxford",
    institution_name: "Oxford",
    country: "United Kingdom",
    region: "Northern Europe",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research"],
    date_signed: getDate(-90),
    date_expiry: getDate(275),
    validity_period: "1 year",
    entry_date: getDate(-90),
    status: "WITHDRAWN",
    agreement_status: "Withdrawn",
    description: "Medical research - withdrawn due to funding constraints.",
    withdrawal_reason: "Insufficient funding allocation",
    withdrawal_date: getDate(-30),
    withdrawn_by: "Dr. Maria Santos",
    point_person_name: "Dr. Maria Santos",
    point_person_email: "maria.santos@university.edu",
    point_person_phone: "+63-2-8888-1234",
    contact_person_name: "Prof. James Wilson",
    contact_person_email: "j.wilson@ox.ac.uk",
    contact_person_phone: "+44-1865-270000",
    university_logo: mkAvatar("Oxford", "002147"),
    logo: mkAvatar("Oxford", "002147"),
    file_path: "/documents/DTS-2024-007.pdf",
    created_at: getDateTime(-90),
    updated_at: getDateTime(-30),
    created_by: "Dr. Sarah Chen",
    updated_by: "Dr. Maria Santos",
  },
  {
    agreement_id: 20,
    dts_number: "DTS-2024-199",
    document_type: "MOU",
    title: "Architecture and Urban Planning",
    partner_name: "Delft University of Technology",
    institution_name: "TU Delft",
    country: "Netherlands",
    region: "Western Europe",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Student Exchange", "Joint Research", "Faculty Exchange"],
    date_signed: getDate(-58),
    date_expiry: getDate(307),
    validity_period: "1 year",
    entry_date: getDate(-58),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Urban planning and sustainable architecture collaboration.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. Jan van der Berg",
    contact_person_email: "j.vanderberg@tudelft.nl",
    contact_person_phone: "+31-15-278-9111",
    university_logo: mkAvatar("TU Delft", "00A6D6"),
    logo: mkAvatar("TU Delft", "00A6D6"),
    file_path: "/documents/DTS-2024-199.pdf",
    created_at: getDateTime(-58),
    updated_at: getDateTime(-6),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 21,
    dts_number: "DTS-2025-035",
    document_type: "MOA",
    title: "International Relations and Policy Studies",
    partner_name: "KU Leuven",
    institution_name: "KU Leuven",
    country: "Belgium",
    region: "Western Europe",
    partnership_type: "Academic Exchange",
    scope_of_partnership: ["Student Exchange", "Faculty Exchange"],
    date_signed: getDate(-15),
    date_expiry: getDate(350),
    validity_period: "1 year",
    entry_date: getDate(-15),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Political science and international relations exchange program.",
    point_person_name: "Prof. Michael O'Connor",
    point_person_email: "m.oconnor@university.edu",
    point_person_phone: "+63-2-8888-1241",
    contact_person_name: "Prof. Pieter Claes",
    contact_person_email: "p.claes@kuleuven.be",
    contact_person_phone: "+32-16-32-1234",
    university_logo: mkAvatar("KU Leuven", "1A4C8C"),
    logo: mkAvatar("KU Leuven", "1A4C8C"),
    file_path: "/documents/DTS-2025-035.pdf",
    created_at: getDateTime(-15),
    updated_at: getDateTime(-1),
    created_by: "Prof. Michael O'Connor",
    updated_by: "Prof. Michael O'Connor",
  },
  {
    agreement_id: 22,
    dts_number: "DTS-2024-203",
    document_type: "MOU",
    title: "Hospitality and Tourism Management",
    partner_name: "École hôtelière de Lausanne",
    institution_name: "EHL",
    country: "Switzerland",
    region: "Western Europe",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Student Exchange", "Internship Programs"],
    date_signed: getDate(-82),
    date_expiry: getDate(283),
    validity_period: "1 year",
    entry_date: getDate(-82),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Premium hospitality management education partnership.",
    point_person_name: "Dr. Aisha Rahman",
    point_person_email: "a.rahman@university.edu",
    point_person_phone: "+63-2-8888-1240",
    contact_person_name: "Prof. Laurent Blanc",
    contact_person_email: "l.blanc@ehl.ch",
    contact_person_phone: "+41-21-785-1111",
    university_logo: mkAvatar("EHL", "C8102E"),
    logo: mkAvatar("EHL", "C8102E"),
    file_path: "/documents/DTS-2024-203.pdf",
    created_at: getDateTime(-82),
    updated_at: getDateTime(-14),
    created_by: "Dr. Aisha Rahman",
    updated_by: "Dr. Aisha Rahman",
  },
  {
    agreement_id: 23,
    dts_number: "DTS-2024-215",
    document_type: "MOU",
    title: "Arts and Cultural Heritage Studies",
    partner_name: "Sapienza University of Rome",
    institution_name: "Sapienza",
    country: "Italy",
    region: "Southern Europe",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs", "Joint Research"],
    date_signed: getDate(-68),
    date_expiry: getDate(297),
    validity_period: "1 year",
    entry_date: getDate(-68),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Art history and cultural heritage preservation partnership.",
    point_person_name: "Prof. Michael O'Connor",
    point_person_email: "m.oconnor@university.edu",
    point_person_phone: "+63-2-8888-1241",
    contact_person_name: "Prof. Giuseppe Rossi",
    contact_person_email: "g.rossi@uniroma1.it",
    contact_person_phone: "+39-06-4991-1234",
    university_logo: mkAvatar("Sapienza", "822433"),
    logo: mkAvatar("Sapienza", "822433"),
    file_path: "/documents/DTS-2024-215.pdf",
    created_at: getDateTime(-68),
    updated_at: getDateTime(-12),
    created_by: "Prof. Michael O'Connor",
    updated_by: "Prof. Michael O'Connor",
  },
  {
    agreement_id: 24,
    dts_number: "DTS-2025-041",
    document_type: "MOA",
    title: "Marine Sciences and Oceanography",
    partner_name: "University of Barcelona",
    institution_name: "UB",
    country: "Spain",
    region: "Southern Europe",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Student Exchange", "Faculty Exchange"],
    date_signed: getDate(-12),
    date_expiry: getDate(353),
    validity_period: "1 year",
    entry_date: getDate(-12),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Marine biology and oceanographic research partnership.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Dr. Carmen Garcia",
    contact_person_email: "c.garcia@ub.edu",
    contact_person_phone: "+34-93-402-1234",
    university_logo: mkAvatar("University of Barcelona", "A61E22"),
    logo: mkAvatar("University of Barcelona", "A61E22"),
    file_path: "/documents/DTS-2025-041.pdf",
    created_at: getDateTime(-12),
    updated_at: getDateTime(-1),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 25,
    dts_number: "DTS-2024-227",
    document_type: "MOU",
    title: "Music and Performing Arts",
    partner_name: "University of Vienna",
    institution_name: "Uni Wien",
    country: "Austria",
    region: "Western Europe",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs"],
    date_signed: getDate(-95),
    date_expiry: getDate(270),
    validity_period: "1 year",
    entry_date: getDate(-95),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Music conservatory and performing arts exchange program.",
    point_person_name: "Prof. Michael O'Connor",
    point_person_email: "m.oconnor@university.edu",
    point_person_phone: "+63-2-8888-1241",
    contact_person_name: "Prof. Wolfgang Schmidt",
    contact_person_email: "w.schmidt@univie.ac.at",
    contact_person_phone: "+43-1-4277-1234",
    university_logo: mkAvatar("University of Vienna", "0063A6"),
    logo: mkAvatar("University of Vienna", "0063A6"),
    file_path: "/documents/DTS-2024-227.pdf",
    created_at: getDateTime(-95),
    updated_at: getDateTime(-17),
    created_by: "Prof. Michael O'Connor",
    updated_by: "Prof. Michael O'Connor",
  },

  // ========== NORTHERN EUROPE ==========
  {
    agreement_id: 26,
    dts_number: "DTS-2024-238",
    document_type: "MOA",
    title: "Sustainable Development and Green Technology",
    partner_name: "KTH Royal Institute of Technology",
    institution_name: "KTH",
    country: "Sweden",
    region: "Northern Europe",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Technology Transfer", "Student Exchange"],
    date_signed: getDate(-105),
    date_expiry: getDate(260),
    validity_period: "1 year",
    entry_date: getDate(-105),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Green technology and sustainability research partnership.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. Erik Svensson",
    contact_person_email: "e.svensson@kth.se",
    contact_person_phone: "+46-8-790-6000",
    university_logo: mkAvatar("KTH", "1954A6"),
    logo: mkAvatar("KTH", "1954A6"),
    file_path: "/documents/DTS-2024-238.pdf",
    created_at: getDateTime(-105),
    updated_at: getDateTime(-19),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 27,
    dts_number: "DTS-2024-249",
    document_type: "MOU",
    title: "Education and Teacher Training",
    partner_name: "University of Oslo",
    institution_name: "UiO",
    country: "Norway",
    region: "Northern Europe",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Faculty Exchange", "Joint Research"],
    date_signed: getDate(-88),
    date_expiry: getDate(277),
    validity_period: "1 year",
    entry_date: getDate(-88),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Teacher education and pedagogical research collaboration.",
    point_person_name: "Prof. Ibrahim Hassan",
    point_person_email: "i.hassan@university.edu",
    point_person_phone: "+63-2-8888-1246",
    contact_person_name: "Prof. Ingrid Larsen",
    contact_person_email: "i.larsen@uio.no",
    contact_person_phone: "+47-22-85-1234",
    university_logo: mkAvatar("University of Oslo", "C7002A"),
    logo: mkAvatar("University of Oslo", "C7002A"),
    file_path: "/documents/DTS-2024-249.pdf",
    created_at: getDateTime(-88),
    updated_at: getDateTime(-16),
    created_by: "Prof. Ibrahim Hassan",
    updated_by: "Prof. Ibrahim Hassan",
  },
  {
    agreement_id: 28,
    dts_number: "DTS-2025-052",
    document_type: "MOU",
    title: "Design and Innovation Studies",
    partner_name: "Aalto University",
    institution_name: "Aalto",
    country: "Finland",
    region: "Northern Europe",
    partnership_type: "Academic Exchange",
    scope_of_partnership: ["Student Exchange", "Joint Research"],
    date_signed: getDate(-8),
    date_expiry: getDate(357),
    validity_period: "1 year",
    entry_date: getDate(-8),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Design thinking and innovation management partnership.",
    point_person_name: "Dr. Sarah Chen",
    point_person_email: "sarah.chen@university.edu",
    point_person_phone: "+63-2-8888-1236",
    contact_person_name: "Prof. Mika Virtanen",
    contact_person_email: "m.virtanen@aalto.fi",
    contact_person_phone: "+358-9-4701-1234",
    university_logo: mkAvatar("Aalto University", "FF6200"),
    logo: mkAvatar("Aalto University", "FF6200"),
    file_path: "/documents/DTS-2025-052.pdf",
    created_at: getDateTime(-8),
    updated_at: getDateTime(-1),
    created_by: "Dr. Sarah Chen",
    updated_by: "Dr. Sarah Chen",
  },
  {
    agreement_id: 29,
    dts_number: "DTS-2024-259",
    document_type: "MOA",
    title: "Public Administration and Governance",
    partner_name: "University of Copenhagen",
    institution_name: "UCPH",
    country: "Denmark",
    region: "Northern Europe",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Faculty Exchange", "Joint Research", "Student Exchange"],
    date_signed: getDate(-77),
    date_expiry: getDate(288),
    validity_period: "1 year",
    entry_date: getDate(-77),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Public policy and governance studies collaboration.",
    point_person_name: "Prof. Michael O'Connor",
    point_person_email: "m.oconnor@university.edu",
    point_person_phone: "+63-2-8888-1241",
    contact_person_name: "Prof. Anders Nielsen",
    contact_person_email: "a.nielsen@ku.dk",
    contact_person_phone: "+45-35-32-1234",
    university_logo: mkAvatar("UCPH", "901A1E"),
    logo: mkAvatar("UCPH", "901A1E"),
    file_path: "/documents/DTS-2024-259.pdf",
    created_at: getDateTime(-77),
    updated_at: getDateTime(-13),
    created_by: "Prof. Michael O'Connor",
    updated_by: "Prof. Michael O'Connor",
  },

  // ========== EASTERN EUROPE ==========
  {
    agreement_id: 30,
    dts_number: "DTS-2024-268",
    document_type: "MOU",
    title: "Computer Science and Software Engineering",
    partner_name: "University of Warsaw",
    institution_name: "UW",
    country: "Poland",
    region: "Eastern Europe",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Student Exchange", "Joint Research"],
    date_signed: getDate(-92),
    date_expiry: getDate(273),
    validity_period: "1 year",
    entry_date: getDate(-92),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Computer science research and software development partnership.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. Andrzej Kowalski",
    contact_person_email: "a.kowalski@uw.edu.pl",
    contact_person_phone: "+48-22-55-20-000",
    university_logo: mkAvatar("University of Warsaw", "5D1C3F"),
    logo: mkAvatar("University of Warsaw", "5D1C3F"),
    file_path: "/documents/DTS-2024-268.pdf",
    created_at: getDateTime(-92),
    updated_at: getDateTime(-18),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 31,
    dts_number: "DTS-2025-063",
    document_type: "MOU",
    title: "Physics and Applied Mathematics",
    partner_name: "Charles University",
    institution_name: "CU",
    country: "Czech Republic",
    region: "Eastern Europe",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Faculty Exchange"],
    date_signed: getDate(-5),
    date_expiry: getDate(360),
    validity_period: "1 year",
    entry_date: getDate(-5),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Theoretical physics and mathematics research collaboration.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. Jan Novák",
    contact_person_email: "j.novak@cuni.cz",
    contact_person_phone: "+420-224-491-111",
    university_logo: mkAvatar("Charles University", "BE1E2D"),
    logo: mkAvatar("Charles University", "BE1E2D"),
    file_path: "/documents/DTS-2025-063.pdf",
    created_at: getDateTime(-5),
    updated_at: getDateTime(-1),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 32,
    dts_number: "DTS-2024-275",
    document_type: "MOU",
    title: "Medical Sciences and Healthcare",
    partner_name: "Semmelweis University",
    institution_name: "Semmelweis",
    country: "Hungary",
    region: "Eastern Europe",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Student Exchange", "Clinical Training"],
    date_signed: getDate(-85),
    date_expiry: getDate(280),
    validity_period: "1 year",
    entry_date: getDate(-85),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Medical education and clinical training partnership.",
    point_person_name: "Dr. Fatima Al-Mansouri",
    point_person_email: "f.almansouri@university.edu",
    point_person_phone: "+63-2-8888-1242",
    contact_person_name: "Dr. István Nagy",
    contact_person_email: "i.nagy@semmelweis.hu",
    contact_person_phone: "+36-1-459-1500",
    university_logo: mkAvatar("Semmelweis", "006341"),
    logo: mkAvatar("Semmelweis", "006341"),
    file_path: "/documents/DTS-2024-275.pdf",
    created_at: getDateTime(-85),
    updated_at: getDateTime(-15),
    created_by: "Dr. Fatima Al-Mansouri",
    updated_by: "Dr. Fatima Al-Mansouri",
  },

  // ========== NORTH AMERICA ==========
  {
    agreement_id: 33,
    dts_number: "DTS-2023-045",
    document_type: "MOA",
    title: "Research Partnership in AI and Robotics",
    partner_name: "Massachusetts Institute of Technology",
    institution_name: "MIT",
    country: "United States",
    region: "North America",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Technology Transfer", "Publication Collaboration"],
    date_signed: getDate(-450),
    date_expiry: getDate(-85),
    validity_period: "1 year",
    entry_date: getDate(-450),
    status: "NEARING_EXPIRATION",
    agreement_status: "Active",
    description: "AI and robotics research partnership.",
    point_person_name: "Dr. Sarah Chen",
    point_person_email: "sarah.chen@university.edu",
    point_person_phone: "+63-2-8888-1236",
    contact_person_name: "Prof. Robert Johnson",
    contact_person_email: "r.johnson@mit.edu",
    contact_person_phone: "+1-617-253-1000",
    university_logo: mkAvatar("MIT", "A31F34"),
    logo: mkAvatar("MIT", "A31F34"),
    file_path: "/documents/DTS-2023-045.pdf",
    created_at: getDateTime(-450),
    updated_at: getDateTime(-5),
    created_by: "Dr. Maria Santos",
    updated_by: "Dr. Sarah Chen",
  },
  {
    agreement_id: 34,
    dts_number: "DTS-2024-286",
    document_type: "MOU",
    title: "Environmental Studies and Climate Science",
    partner_name: "Stanford University",
    institution_name: "Stanford",
    country: "United States",
    region: "North America",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Student Exchange"],
    date_signed: getDate(-70),
    date_expiry: getDate(295),
    validity_period: "1 year",
    entry_date: getDate(-70),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Climate change and environmental sustainability research.",
    point_person_name: "Carlos Martinez",
    point_person_email: "c.martinez@university.edu",
    point_person_phone: "+63-2-8888-1243",
    contact_person_name: "Prof. Sarah Williams",
    contact_person_email: "s.williams@stanford.edu",
    contact_person_phone: "+1-650-723-2300",
    university_logo: mkAvatar("Stanford", "8C1515"),
    logo: mkAvatar("Stanford", "8C1515"),
    file_path: "/documents/DTS-2024-286.pdf",
    created_at: getDateTime(-70),
    updated_at: getDateTime(-11),
    created_by: "Carlos Martinez",
    updated_by: "Carlos Martinez",
  },
  {
    agreement_id: 35,
    dts_number: "DTS-2022-089",
    document_type: "MOA",
    title: "Joint Degree Program in Business",
    partner_name: "University of Toronto",
    institution_name: "U of T",
    country: "Canada",
    region: "North America",
    partnership_type: "Dual Degree Program",
    scope_of_partnership: ["Dual Degree Programs", "Student Exchange"],
    date_signed: getDate(-800),
    date_expiry: getDate(-70),
    validity_period: "2 years",
    entry_date: getDate(-800),
    status: "EXPIRED",
    agreement_status: "Expired",
    description: "MBA dual degree program - expired.",
    point_person_name: "Dr. Sarah Chen",
    point_person_email: "sarah.chen@university.edu",
    point_person_phone: "+63-2-8888-1236",
    contact_person_name: "Dr. Jennifer Smith",
    contact_person_email: "j.smith@utoronto.ca",
    contact_person_phone: "+1-416-978-2011",
    university_logo: mkAvatar("University of Toronto", "00204E"),
    logo: mkAvatar("University of Toronto", "00204E"),
    file_path: "/documents/DTS-2022-089.pdf",
    created_at: getDateTime(-800),
    updated_at: getDateTime(-70),
    created_by: "Dr. Maria Santos",
    updated_by: "Dr. Sarah Chen",
  },
  {
    agreement_id: 36,
    dts_number: "DTS-2025-074",
    document_type: "MOU",
    title: "Latin American Studies and Culture",
    partner_name: "Universidad Nacional Autónoma de México",
    institution_name: "UNAM",
    country: "Mexico",
    region: "North America",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs"],
    date_signed: getDate(-3),
    date_expiry: getDate(362),
    validity_period: "1 year",
    entry_date: getDate(-3),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Latin American cultural studies and language exchange.",
    point_person_name: "Carlos Martinez",
    point_person_email: "c.martinez@university.edu",
    point_person_phone: "+63-2-8888-1243",
    contact_person_name: "Dr. María Hernández",
    contact_person_email: "m.hernandez@unam.mx",
    contact_person_phone: "+52-55-5622-1234",
    university_logo: mkAvatar("UNAM", "0B2F6D"),
    logo: mkAvatar("UNAM", "0B2F6D"),
    file_path: "/documents/DTS-2025-074.pdf",
    created_at: getDateTime(-3),
    updated_at: getDateTime(-1),
    created_by: "Carlos Martinez",
    updated_by: "Carlos Martinez",
  },

  // ========== SOUTH AMERICA ==========
  {
    agreement_id: 37,
    dts_number: "DTS-2024-294",
    document_type: "MOA",
    title: "Tropical Agriculture and Biodiversity",
    partner_name: "University of São Paulo",
    institution_name: "USP",
    country: "Brazil",
    region: "South America",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Student Exchange", "Faculty Exchange"],
    date_signed: getDate(-62),
    date_expiry: getDate(303),
    validity_period: "1 year",
    entry_date: getDate(-62),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Tropical agriculture and biodiversity conservation research.",
    point_person_name: "Carlos Martinez",
    point_person_email: "c.martinez@university.edu",
    point_person_phone: "+63-2-8888-1243",
    contact_person_name: "Prof. Paulo Silva",
    contact_person_email: "p.silva@usp.br",
    contact_person_phone: "+55-11-3091-3500",
    university_logo: mkAvatar("USP", "003874"),
    logo: mkAvatar("USP", "003874"),
    file_path: "/documents/DTS-2024-294.pdf",
    created_at: getDateTime(-62),
    updated_at: getDateTime(-9),
    created_by: "Carlos Martinez",
    updated_by: "Carlos Martinez",
  },
  {
    agreement_id: 38,
    dts_number: "DTS-2025-085",
    document_type: "MOU",
    title: "Social Sciences and Development",
    partner_name: "University of Buenos Aires",
    institution_name: "UBA",
    country: "Argentina",
    region: "South America",
    partnership_type: "Academic Exchange",
    scope_of_partnership: ["Student Exchange", "Joint Research"],
    date_signed: getDate(-2),
    date_expiry: getDate(363),
    validity_period: "1 year",
    entry_date: getDate(-2),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Social development and economic research partnership.",
    point_person_name: "Carlos Martinez",
    point_person_email: "c.martinez@university.edu",
    point_person_phone: "+63-2-8888-1243",
    contact_person_name: "Dr. Gabriela Fernández",
    contact_person_email: "g.fernandez@uba.ar",
    contact_person_phone: "+54-11-5285-1234",
    university_logo: mkAvatar("UBA", "0033A0"),
    logo: mkAvatar("UBA", "0033A0"),
    file_path: "/documents/DTS-2025-085.pdf",
    created_at: getDateTime(-2),
    updated_at: getDateTime(-1),
    created_by: "Carlos Martinez",
    updated_by: "Carlos Martinez",
  },
  {
    agreement_id: 39,
    dts_number: "DTS-2024-305",
    document_type: "MOU",
    title: "Engineering and Mining Technology",
    partner_name: "Pontificia Universidad Católica de Chile",
    institution_name: "PUC Chile",
    country: "Chile",
    region: "South America",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Student Exchange", "Joint Research"],
    date_signed: getDate(-53),
    date_expiry: getDate(312),
    validity_period: "1 year",
    entry_date: getDate(-53),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Mining engineering and sustainable resource management.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. Diego Vargas",
    contact_person_email: "d.vargas@uc.cl",
    contact_person_phone: "+56-2-2354-1234",
    university_logo: mkAvatar("PUC Chile", "003DA5"),
    logo: mkAvatar("PUC Chile", "003DA5"),
    file_path: "/documents/DTS-2024-305.pdf",
    created_at: getDateTime(-53),
    updated_at: getDateTime(-7),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 40,
    dts_number: "DTS-2024-316",
    document_type: "MOU",
    title: "Public Health and Urban Development",
    partner_name: "Universidad de los Andes",
    institution_name: "Uniandes Colombia",
    country: "Colombia",
    region: "South America",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Faculty Exchange"],
    date_signed: getDate(-44),
    date_expiry: getDate(321),
    validity_period: "1 year",
    entry_date: getDate(-44),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Urban public health and sustainable cities research.",
    point_person_name: "Carlos Martinez",
    point_person_email: "c.martinez@university.edu",
    point_person_phone: "+63-2-8888-1243",
    contact_person_name: "Prof. Andrea Gómez",
    contact_person_email: "a.gomez@uniandes.edu.co",
    contact_person_phone: "+57-1-339-4949",
    university_logo: mkAvatar("Uniandes Colombia", "FFCD00"),
    logo: mkAvatar("Uniandes Colombia", "FFCD00"),
    file_path: "/documents/DTS-2024-316.pdf",
    created_at: getDateTime(-44),
    updated_at: getDateTime(-6),
    created_by: "Carlos Martinez",
    updated_by: "Carlos Martinez",
  },

  // ========== OCEANIA ==========
  {
    agreement_id: 41,
    dts_number: "DTS-2024-032",
    document_type: "MOA",
    title: "Higher Education Partnership",
    partner_name: "University of Sydney",
    institution_name: "University of Sydney",
    country: "Australia",
    region: "Oceania",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Dual Degree Programs", "Student Exchange", "Joint Research", "Faculty Exchange"],
    date_signed: getDate(-120),
    date_expiry: getDate(610),
    validity_period: "2 years",
    entry_date: getDate(-120),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Comprehensive academic partnership with dual degree programs.",
    point_person_name: "Dr. Sarah Chen",
    point_person_email: "sarah.chen@university.edu",
    point_person_phone: "+63-2-8888-1236",
    contact_person_name: "Dr. Emily Thompson",
    contact_person_email: "emily.thompson@sydney.edu.au",
    contact_person_phone: "+61-2-9351-2222",
    university_logo: mkAvatar("University of Sydney", "0D3C61"),
    logo: mkAvatar("University of Sydney", "0D3C61"),
    file_path: "/documents/DTS-2024-032.pdf",
    created_at: getDateTime(-120),
    updated_at: getDateTime(-15),
    created_by: "Dr. Maria Santos",
    updated_by: "Dr. Sarah Chen",
  },
  {
    agreement_id: 42,
    dts_number: "DTS-2024-327",
    document_type: "MOU",
    title: "Indigenous Studies and Cultural Preservation",
    partner_name: "University of Auckland",
    institution_name: "Auckland",
    country: "New Zealand",
    region: "Oceania",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs", "Joint Research"],
    date_signed: getDate(-37),
    date_expiry: getDate(328),
    validity_period: "1 year",
    entry_date: getDate(-37),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Indigenous cultures and heritage preservation partnership.",
    point_person_name: "Dr. Aisha Rahman",
    point_person_email: "a.rahman@university.edu",
    point_person_phone: "+63-2-8888-1240",
    contact_person_name: "Prof. Aroha Williams",
    contact_person_email: "a.williams@auckland.ac.nz",
    contact_person_phone: "+64-9-373-7999",
    university_logo: mkAvatar("University of Auckland", "00467F"),
    logo: mkAvatar("University of Auckland", "00467F"),
    file_path: "/documents/DTS-2024-327.pdf",
    created_at: getDateTime(-37),
    updated_at: getDateTime(-5),
    created_by: "Dr. Aisha Rahman",
    updated_by: "Dr. Aisha Rahman",
  },

  // ========== AFRICA ==========
  {
    agreement_id: 43,
    dts_number: "DTS-2024-338",
    document_type: "MOA",
    title: "Energy and Sustainable Development",
    partner_name: "University of Cape Town",
    institution_name: "UCT",
    country: "South Africa",
    region: "Africa",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Student Exchange", "Faculty Exchange"],
    date_signed: getDate(-50),
    date_expiry: getDate(315),
    validity_period: "1 year",
    entry_date: getDate(-50),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Renewable energy and sustainable development research.",
    point_person_name: "Dr. Fatima Al-Mansouri",
    point_person_email: "f.almansouri@university.edu",
    point_person_phone: "+63-2-8888-1242",
    contact_person_name: "Prof. Thabo Mbeki",
    contact_person_email: "t.mbeki@uct.ac.za",
    contact_person_phone: "+27-21-650-9111",
    university_logo: mkAvatar("UCT", "003B5C"),
    logo: mkAvatar("UCT", "003B5C"),
    file_path: "/documents/DTS-2024-338.pdf",
    created_at: getDateTime(-50),
    updated_at: getDateTime(-8),
    created_by: "Dr. Fatima Al-Mansouri",
    updated_by: "Dr. Fatima Al-Mansouri",
  },
  {
    agreement_id: 44,
    dts_number: "DTS-2025-096",
    document_type: "MOU",
    title: "Ancient Civilizations and Archaeology",
    partner_name: "Cairo University",
    institution_name: "Cairo University",
    country: "Egypt",
    region: "Africa",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Joint Research", "Student Exchange"],
    date_signed: getDate(-1),
    date_expiry: getDate(364),
    validity_period: "1 year",
    entry_date: getDate(-1),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Egyptology and ancient civilizations research partnership.",
    point_person_name: "Dr. Fatima Al-Mansouri",
    point_person_email: "f.almansouri@university.edu",
    point_person_phone: "+63-2-8888-1242",
    contact_person_name: "Prof. Ahmed Hassan",
    contact_person_email: "a.hassan@cu.edu.eg",
    contact_person_phone: "+20-2-3567-1234",
    university_logo: mkAvatar("Cairo University", "8B0000"),
    logo: mkAvatar("Cairo University", "8B0000"),
    file_path: "/documents/DTS-2025-096.pdf",
    created_at: getDateTime(-1),
    updated_at: getDateTime(-1),
    created_by: "Dr. Fatima Al-Mansouri",
    updated_by: "Dr. Fatima Al-Mansouri",
  },
  {
    agreement_id: 45,
    dts_number: "DTS-2024-349",
    document_type: "MOU",
    title: "Wildlife Conservation and Ecology",
    partner_name: "University of Nairobi",
    institution_name: "UoN",
    country: "Kenya",
    region: "Africa",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Field Studies"],
    date_signed: getDate(-41),
    date_expiry: getDate(324),
    validity_period: "1 year",
    entry_date: getDate(-41),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Wildlife conservation and ecological research in East Africa.",
    point_person_name: "Dr. Rajesh Kumar",
    point_person_email: "r.kumar@university.edu",
    point_person_phone: "+63-2-8888-1248",
    contact_person_name: "Dr. Joseph Kimani",
    contact_person_email: "j.kimani@uonbi.ac.ke",
    contact_person_phone: "+254-20-318-262",
    university_logo: mkAvatar("University of Nairobi", "003E7E"),
    logo: mkAvatar("University of Nairobi", "003E7E"),
    file_path: "/documents/DTS-2024-349.pdf",
    created_at: getDateTime(-41),
    updated_at: getDateTime(-6),
    created_by: "Dr. Rajesh Kumar",
    updated_by: "Dr. Rajesh Kumar",
  },
  {
    agreement_id: 46,
    dts_number: "DTS-2024-358",
    document_type: "MOU",
    title: "African Languages and Literature",
    partner_name: "University of Lagos",
    institution_name: "UNILAG",
    country: "Nigeria",
    region: "Africa",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs"],
    date_signed: getDate(-32),
    date_expiry: getDate(333),
    validity_period: "1 year",
    entry_date: getDate(-32),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "African literature and linguistic studies exchange program.",
    point_person_name: "Dr. Fatima Al-Mansouri",
    point_person_email: "f.almansouri@university.edu",
    point_person_phone: "+63-2-8888-1242",
    contact_person_name: "Prof. Chidinma Okafor",
    contact_person_email: "c.okafor@unilag.edu.ng",
    contact_person_phone: "+234-1-493-4335",
    university_logo: mkAvatar("UNILAG", "006633"),
    logo: mkAvatar("UNILAG", "006633"),
    file_path: "/documents/DTS-2024-358.pdf",
    created_at: getDateTime(-32),
    updated_at: getDateTime(-4),
    created_by: "Dr. Fatima Al-Mansouri",
    updated_by: "Dr. Fatima Al-Mansouri",
  },

  // ========== MIDDLE EAST ==========
  {
    agreement_id: 47,
    dts_number: "DTS-2024-367",
    document_type: "MOA",
    title: "Smart Cities and Urban Innovation",
    partner_name: "United Arab Emirates University",
    institution_name: "UAEU",
    country: "United Arab Emirates",
    region: "Western Asia",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Technology Transfer", "Student Exchange"],
    date_signed: getDate(-28),
    date_expiry: getDate(337),
    validity_period: "1 year",
    entry_date: getDate(-28),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Smart cities technology and urban planning innovation.",
    point_person_name: "Dr. Fatima Al-Mansouri",
    point_person_email: "f.almansouri@university.edu",
    point_person_phone: "+63-2-8888-1242",
    contact_person_name: "Dr. Mohammed Al-Zaabi",
    contact_person_email: "m.alzaabi@uaeu.ac.ae",
    contact_person_phone: "+971-3-713-5555",
    university_logo: mkAvatar("UAEU", "009639"),
    logo: mkAvatar("UAEU", "009639"),
    file_path: "/documents/DTS-2024-367.pdf",
    created_at: getDateTime(-28),
    updated_at: getDateTime(-3),
    created_by: "Dr. Fatima Al-Mansouri",
    updated_by: "Dr. Fatima Al-Mansouri",
  },
  {
    agreement_id: 48,
    dts_number: "DTS-2024-376",
    document_type: "MOU",
    title: "Technology and Entrepreneurship",
    partner_name: "Technion - Israel Institute of Technology",
    institution_name: "Technion",
    country: "Israel",
    region: "Western Asia",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Joint Research", "Student Exchange", "Innovation Programs"],
    date_signed: getDate(-24),
    date_expiry: getDate(341),
    validity_period: "1 year",
    entry_date: getDate(-24),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Technology innovation and startup incubation partnership.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Prof. David Cohen",
    contact_person_email: "d.cohen@technion.ac.il",
    contact_person_phone: "+972-4-829-2111",
    university_logo: mkAvatar("Technion", "003D79"),
    logo: mkAvatar("Technion", "003D79"),
    file_path: "/documents/DTS-2024-376.pdf",
    created_at: getDateTime(-24),
    updated_at: getDateTime(-2),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },
  {
    agreement_id: 49,
    dts_number: "DTS-2024-385",
    document_type: "MOU",
    title: "History and Middle Eastern Studies",
    partner_name: "Boğaziçi University",
    institution_name: "Boğaziçi",
    country: "Turkey",
    region: "Western Asia",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs", "Joint Research"],
    date_signed: getDate(-18),
    date_expiry: getDate(347),
    validity_period: "1 year",
    entry_date: getDate(-18),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Middle Eastern history and cultural studies partnership.",
    point_person_name: "Dr. Fatima Al-Mansouri",
    point_person_email: "f.almansouri@university.edu",
    point_person_phone: "+63-2-8888-1242",
    contact_person_name: "Prof. Ayşe Yılmaz",
    contact_person_email: "a.yilmaz@boun.edu.tr",
    contact_person_phone: "+90-212-359-6000",
    university_logo: mkAvatar("Boğaziçi", "003171"),
    logo: mkAvatar("Boğaziçi", "003171"),
    file_path: "/documents/DTS-2024-385.pdf",
    created_at: getDateTime(-18),
    updated_at: getDateTime(-2),
    created_by: "Dr. Fatima Al-Mansouri",
    updated_by: "Dr. Fatima Al-Mansouri",
  },
  {
    agreement_id: 50,
    dts_number: "DTS-2025-107",
    document_type": "MOA",
    title: "Petroleum Engineering and Energy",
    partner_name: "King Fahd University of Petroleum and Minerals",
    institution_name: "KFUPM",
    country: "Saudi Arabia",
    region: "Western Asia",
    partnership_type: "Research Collaboration",
    scope_of_partnership: ["Joint Research", "Faculty Exchange"],
    date_signed: getDate(0),
    date_expiry: getDate(365),
    validity_period: "1 year",
    entry_date: getDate(0),
    status: "ACTIVE",
    agreement_status: "Active",
    description: "Petroleum engineering and renewable energy transition research.",
    point_person_name: "Dr. Roberto Gonzales",
    point_person_email: "r.gonzales@university.edu",
    point_person_phone: "+63-2-8888-1239",
    contact_person_name: "Dr. Abdullah Al-Saud",
    contact_person_email: "a.alsaud@kfupm.edu.sa",
    contact_person_phone: "+966-13-860-0000",
    university_logo: mkAvatar("KFUPM", "006233"),
    logo: mkAvatar("KFUPM", "006233"),
    file_path: "/documents/DTS-2025-107.pdf",
    created_at: getDateTime(0),
    updated_at: getDateTime(0),
    created_by: "Dr. Roberto Gonzales",
    updated_by: "Dr. Roberto Gonzales",
  },

  // ========== MORE EXPIRED AGREEMENTS ==========
  {
    agreement_id: 51,
    dts_number: "DTS-2022-056",
    document_type: "MOU",
    title: "Academic Cooperation Agreement",
    partner_name: "Peking University",
    institution_name: "Peking University",
    country: "China",
    region: "Eastern Asia",
    partnership_type: "Academic Exchange",
    scope_of_partnership: ["Student Exchange", "Faculty Exchange"],
    date_signed: getDate(-730),
    date_expiry: getDate(-365),
    validity_period: "1 year",
    entry_date: getDate(-730),
    status: "EXPIRED",
    agreement_status: "Expired",
    description: "Humanities and social sciences exchange - expired.",
    point_person_name: "Prof. John Reyes",
    point_person_email: "john.reyes@university.edu",
    point_person_phone: "+63-2-8888-1235",
    contact_person_name: "Prof. Wang Li",
    contact_person_email: "wangli@pku.edu.cn",
    contact_person_phone: "+86-10-6275-1230",
    university_logo: mkAvatar("Peking University", "A31F34"),
    logo: mkAvatar("Peking University", "A31F34"),
    file_path: "/documents/DTS-2022-056.pdf",
    created_at: getDateTime(-730),
    updated_at: getDateTime(-365),
    created_by: "Dr. Maria Santos",
    updated_by: "Prof. John Reyes",
  },
  {
    agreement_id: 52,
    dts_number: "DTS-2021-112",
    document_type: "MOU",
    title: "Language and Cultural Studies",
    partner_name: "Kyoto University",
    institution_name: "Kyoto University",
    country: "Japan",
    region: "Eastern Asia",
    partnership_type: "Cultural Exchange",
    scope_of_partnership: ["Student Exchange", "Cultural Programs"],
    date_signed: getDate(-900),
    date_expiry: getDate(-535),
    validity_period: "1 year",
    entry_date: getDate(-900),
    status: "EXPIRED",
    agreement_status: "Expired",
    description: "Japanese language and cultural exchange - expired.",
    point_person_name: "Dr. Yuki Nakamura",
    point_person_email: "y.nakamura@university.edu",
    point_person_phone: "+63-2-8888-1244",
    contact_person_name: "Prof. Kenji Yamamoto",
    contact_person_email: "k.yamamoto@kyoto-u.ac.jp",
    contact_person_phone: "+81-75-753-7531",
    university_logo: mkAvatar("Kyoto University", "003F87"),
    logo: mkAvatar("Kyoto University", "003F87"),
    file_path: "/documents/DTS-2021-112.pdf",
    created_at: getDateTime(-900),
    updated_at: getDateTime(-535),
    created_by: "Dr. Yuki Nakamura",
    updated_by: "Dr. Yuki Nakamura",
  },
  {
    agreement_id: 53,
    dts_number: "DTS-2021-078",
    document_type: "MOA",
    title: "Law and Governance Studies",
    partner_name: "Harvard University",
    institution_name: "Harvard",
    country: "United States",
    region: "North America",
    partnership_type: "Academic Partnership",
    scope_of_partnership: ["Faculty Exchange", "Joint Research"],
    date_signed: getDate(-850),
    date_expiry: getDate(-485),
    validity_period: "1 year",
    entry_date: getDate(-850),
    status: "EXPIRED",
    agreement_status: "Expired",
    description: "Law school partnership - expired.",
    point_person_name: "Prof. Michael O'Connor",
    point_person_email: "m.oconnor@university.edu",
    point_person_phone: "+63-2-8888-1241",
    contact_person_name: "Prof. Elizabeth Warren",
    contact_person_email: "e.warren@harvard.edu",
    contact_person_phone: "+1-617-495-1000",
    university_logo: mkAvatar("Harvard", "A51C30"),
    logo: mkAvatar("Harvard", "A51C30"),
    file_path: "/documents/DTS-2021-078.pdf",
    created_at: getDateTime(-850),
    updated_at: getDateTime(-485),
    created_by: "Prof. Michael O'Connor",
    updated_by: "Prof. Michael O'Connor",
  },
];
