// This file contains the expanded dummy data collections
// Copy these arrays to replace the corresponding sections in adminDummyData.js

// ====================================
// EXPANDED AUDIT LOGS (40+ entries)
// ====================================
export const EXPANDED_AUDIT_LOGS = [
  {
    id: 1,
    action: "Login",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(0, -5),
    ip_address: "192.168.1.100",
    details: "Successful login from office network",
  },
  {
    id: 2,
    action: "Agreement Created",
    user: "Prof. John Reyes",
    user_id: 2,
    timestamp: getDateTime(0, -4),
    ip_address: "192.168.1.101",
    details: "Created new MOU agreement DTS-2024-001 with Tokyo International University",
    entity_type: "agreement",
    entity_id: 1,
  },
  {
    id: 3,
    action: "Document Uploaded",
    user: "Dr. Sarah Chen",
    user_id: 3,
    timestamp: getDateTime(0, -3),
    ip_address: "192.168.1.102",
    details: "Uploaded document version 3 for DTS-2024-001",
    entity_type: "document",
    entity_id: 3,
  },
  {
    id: 4,
    action: "Agreement Updated",
    user: "Prof. John Reyes",
    user_id: 2,
    timestamp: getDateTime(0, -2),
    ip_address: "192.168.1.101",
    details: "Updated contact information for agreement DTS-2023-045",
    entity_type: "agreement",
    entity_id: 2,
  },
  {
    id: 5,
    action: "User Registration Approved",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-1, -5),
    ip_address: "192.168.1.100",
    details: "Approved registration request from Michael Wong",
    entity_type: "registration",
    entity_id: 3,
  },
  {
    id: 6,
    action: "Email Sent",
    user: "System",
    user_id: null,
    timestamp: getDateTime(-1, -4),
    ip_address: "system",
    details: "Expiration reminder sent for DTS-2024-015 (30 days notice)",
    entity_type: "email",
  },
  {
    id: 7,
    action: "Agreement Archived",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-2, 0),
    ip_address: "192.168.1.100",
    details: "Archived expired agreement DTS-2022-056",
    entity_type: "agreement",
    entity_id: 8,
  },
  {
    id: 8,
    action: "Agreement Withdrawn",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-30, 0),
    ip_address: "192.168.1.100",
    details: "Withdrew agreement DTS-2024-007 - Reason: Insufficient funding",
    entity_type: "agreement",
    entity_id: 10,
  },
  {
    id: 9,
    action: "Report Generated",
    user: "Dr. Sarah Chen",
    user_id: 3,
    timestamp: getDateTime(-3, 0),
    ip_address: "192.168.1.102",
    details: "Generated monthly partnership report (CSV)",
    entity_type: "report",
  },
  {
    id: 10,
    action: "Login Failed",
    user: "Unknown",
    user_id: null,
    timestamp: getDateTime(-5, 0),
    ip_address: "203.45.67.89",
    details: "Failed login attempt for email: unauthorized@example.com",
  },
  {
    id: 11,
    action: "Document Version Created",
    user: "Prof. John Reyes",
    user_id: 2,
    timestamp: getDateTime(-4, -2),
    ip_address: "192.168.1.101",
    details: "Created new document version for DTS-2024-188",
    entity_type: "document",
    entity_id: 13,
  },
  {
    id: 12,
    action: "Login",
    user: "Dr. Sarah Chen",
    user_id: 3,
    timestamp: getDateTime(-1, -8),
    ip_address: "192.168.1.102",
    details: "Successful login from home network",
  },
  {
    id: 13,
    action: "Agreement Updated",
    user: "Dr. Roberto Gonzales",
    user_id: 9,
    timestamp: getDateTime(-2, -3),
    ip_address: "192.168.1.145",
    details: "Updated scope of partnership for DTS-2024-145 (IIT Delhi)",
    entity_type: "agreement",
    entity_id: 11,
  },
  {
    id: 14,
    action: "User Registration Rejected",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-5, -1),
    ip_address: "192.168.1.100",
    details: "Rejected registration request - Reason: Incomplete documentation",
    entity_type: "registration",
    entity_id: 7,
  },
  {
    id: 15,
    action: "Agreement Created",
    user: "Prof. Michael O'Connor",
    user_id: 7,
    timestamp: getDateTime(-8, 0),
    ip_address: "192.168.1.143",
    details: "Created new partnership agreement DTS-2024-188 with Sorbonne University",
    entity_type: "agreement",
    entity_id: 15,
  },
  {
    id: 16,
    action: "Email Sent",
    user: "System",
    user_id: null,
    timestamp: getDateTime(-10, 0),
    ip_address: "system",
    details: "Welcome email sent to new user: Ana Garcia",
    entity_type: "email",
  },
  {
    id: 17,
    action: "Document Uploaded",
    user: "Dr. Aisha Rahman",
    user_id: 8,
    timestamp: getDateTime(-6, -4),
    ip_address: "192.168.1.144",
    details: "Uploaded signed document for DTS-2025-027 (University of Dhaka)",
    entity_type: "document",
    entity_id: 8,
  },
  {
    id: 18,
    action: "Login",
    user: "Prof. Michael O'Connor",
    user_id: 7,
    timestamp: getDateTime(-3, -6),
    ip_address: "192.168.1.143",
    details: "Successful login from office network",
  },
  {
    id: 19,
    action: "Agreement Expiration Warning",
    user: "System",
    user_id: null,
    timestamp: getDateTime(-15, 0),
    ip_address: "system",
    details: "Generated expiration warning for DTS-2024-015 (NUS) - 30 days remaining",
    entity_type: "agreement",
    entity_id: 6,
  },
  {
    id: 20,
    action: "Report Generated",
    user: "Dr. Fatima Al-Mansouri",
    user_id: 10,
    timestamp: getDateTime(-7, 0),
    ip_address: "192.168.1.146",
    details: "Generated regional partnership report for Middle East & Africa",
    entity_type: "report",
  },
  {
    id: 21,
    action: "User Profile Updated",
    user: "Dr. Sarah Chen",
    user_id: 3,
    timestamp: getDateTime(-9, -2),
    ip_address: "192.168.1.102",
    details: "Updated profile picture and contact information",
    entity_type: "user",
    entity_id: 3,
  },
  {
    id: 22,
    action: "Agreement Withdrawn",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-25, 0),
    ip_address: "192.168.1.100",
    details: "Withdrew agreement DTS-2023-098 (Seoul National) - Reason: Partner request",
    entity_type: "agreement",
    entity_id: 5,
  },
  {
    id: 23,
    action: "Document Version Archived",
    user: "Prof. John Reyes",
    user_id: 2,
    timestamp: getDateTime(-12, 0),
    ip_address: "192.168.1.101",
    details: "Archived old document version for DTS-2024-001",
    entity_type: "document",
    entity_id: 1,
  },
  {
    id: 24,
    action: "Login",
    user: "Dr. Roberto Gonzales",
    user_id: 9,
    timestamp: getDateTime(-4, -5),
    ip_address: "192.168.1.145",
    details: "Successful login from office network",
  },
  {
    id: 25,
    action: "Email Template Updated",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-18, 0),
    ip_address: "192.168.1.100",
    details: "Updated expiration reminder template",
    entity_type: "email_template",
    entity_id: 2,
  },
  {
    id: 26,
    action: "Agreement Created",
    user: "Dr. Roberto Gonzales",
    user_id: 9,
    timestamp: getDateTime(-42, 0),
    ip_address: "192.168.1.145",
    details: "Created new agreement DTS-2024-395 with NTU Singapore",
    entity_type: "agreement",
    entity_id: 45,
  },
  {
    id: 27,
    action: "User Registration Approved",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-20, 0),
    ip_address: "192.168.1.100",
    details: "Approved registration request from David Kim",
    entity_type: "registration",
    entity_id: 1,
  },
  {
    id: 28,
    action: "Document Uploaded",
    user: "Prof. Ibrahim Hassan",
    user_id: 11,
    timestamp: getDateTime(-14, -3),
    ip_address: "192.168.1.147",
    details: "Uploaded new document version for DTS-2024-358 (UAEU)",
    entity_type: "document",
    entity_id: 23,
  },
  {
    id: 29,
    action: "Agreement Updated",
    user: "Dr. Rajesh Kumar",
    user_id: 13,
    timestamp: getDateTime(-16, -1),
    ip_address: "192.168.1.149",
    details: "Updated validity period for DTS-2024-176 (University of Colombo)",
    entity_type: "agreement",
    entity_id: 14,
  },
  {
    id: 30,
    action: "Login Failed",
    user: "Unknown",
    user_id: null,
    timestamp: getDateTime(-22, 0),
    ip_address: "45.67.89.123",
    details: "Failed login attempt for email: test@example.com",
  },
  {
    id: 31,
    action: "Report Generated",
    user: "Prof. John Reyes",
    user_id: 2,
    timestamp: getDateTime(-28, 0),
    ip_address: "192.168.1.101",
    details: "Generated quarterly partnership statistics report (PDF)",
    entity_type: "report",
  },
  {
    id: 32,
    action: "Email Sent",
    user: "System",
    user_id: null,
    timestamp: getDateTime(-35, 0),
    ip_address: "system",
    details: "Expiration reminder sent for DTS-2024-022 (TU Munich) - 15 days notice",
    entity_type: "email",
  },
  {
    id: 33,
    action: "Agreement Archived",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-40, 0),
    ip_address: "192.168.1.100",
    details: "Archived expired agreement DTS-2021-112 (Kyoto University)",
    entity_type: "agreement",
    entity_id: 44,
  },
  {
    id: 34,
    action: "Login",
    user: "Dr. Fatima Al-Mansouri",
    user_id: 10,
    timestamp: getDateTime(-11, -7),
    ip_address: "192.168.1.146",
    details: "Successful login from office network",
  },
  {
    id: 35,
    action: "User Registration Approved",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-45, 0),
    ip_address: "192.168.1.100",
    details: "Approved registration request from Emily Watson",
    entity_type: "registration",
    entity_id: 5,
  },
  {
    id: 36,
    action: "Document Uploaded",
    user: "Dr. Roberto Gonzales",
    user_id: 9,
    timestamp: getDateTime(-33, 0),
    ip_address: "192.168.1.145",
    details: "Uploaded final signed agreement for DTS-2024-408 (Heidelberg)",
    entity_type: "document",
    entity_id: 28,
  },
  {
    id: 37,
    action: "Agreement Created",
    user: "Prof. Michael O'Connor",
    user_id: 7,
    timestamp: getDateTime(-55, 0),
    ip_address: "192.168.1.143",
    details: "Created new agreement DTS-2024-167 with Aga Khan University",
    entity_type: "agreement",
    entity_id: 12,
  },
  {
    id: 38,
    action: "Email Sent",
    user: "System",
    user_id: null,
    timestamp: getDateTime(-50, 0),
    ip_address: "system",
    details: "Registration rejection notification sent",
    entity_type: "email",
  },
  {
    id: 39,
    action: "Agreement Withdrawn",
    user: "Dr. Maria Santos",
    user_id: 1,
    timestamp: getDateTime(-60, 0),
    ip_address: "192.168.1.100",
    details: "Withdrew agreement DTS-2024-215 (Sapienza) - Reason: Policy changes",
    entity_type: "agreement",
    entity_id: 19,
  },
  {
    id: 40,
    action: "Report Generated",
    user: "Dr. Sarah Chen",
    user_id: 3,
    timestamp: getDateTime(-65, 0),
    ip_address: "192.168.1.102",
    details: "Generated annual comprehensive partnership report",
    entity_type: "report",
  },
  {
    id: 41,
    action: "Login",
    user: "Prof. Ibrahim Hassan",
    user_id: 11,
    timestamp: getDateTime(-13, -4),
    ip_address: "192.168.1.147",
    details: "Successful login from home network",
  },
  {
    id: 42,
    action: "Agreement Updated",
    user: "Dr. Aisha Rahman",
    user_id: 8,
    timestamp: getDateTime(-21, -2),
    ip_address: "192.168.1.144",
    details: "Updated contact person for DTS-2025-027",
    entity_type: "agreement",
    entity_id: 13,
  },
];

// Note: Copy getDateTime and getDate helper functions to use this data
// This is a template for expansion - integrate into adminDummyData.js
